"""``imp figures``: aggregate a sweep run into the paper's summary artifacts.

Reads a run's ``metrics_long.csv`` and writes, next to it:

* ``summary.csv`` -- mean and standard deviation per (method, target, metric)
  over seeds, the table the manuscript's results tables are built from.
* ``summary.tex`` -- the same aggregation as a LaTeX ``tabular`` for direct
  ``\\input`` into ``paper/tables/`` (written with plain string formatting, so
  no jinja2/matplotlib dependency).

Plots (per-metric method comparisons) are TODO and land behind the ``viz``
extra; tables come first because the paper's claims cite them.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def _to_latex_tabular(summary: pd.DataFrame) -> str:
    """Render the summary frame as a plain LaTeX tabular (no jinja2)."""
    lines = [
        "% Generated by `imp figures` -- do not edit by hand.",
        r"\begin{tabular}{llrrr}",
        r"\hline",
        r"method & target & metric & mean & sd \\",
        r"\hline",
    ]
    for record in summary.itertuples(index=False):
        method = str(record.method).replace("_", r"\_")
        target = str(record.target).replace("_", r"\_")
        metric = str(record.metric).replace("_", r"\_")
        lines.append(
            f"{method} & {target} & {metric} & "
            f"{record.mean:,.4f} & {record.sd:,.4f} \\\\"
        )
    lines += [r"\hline", r"\end{tabular}", ""]
    return "\n".join(lines)


def _aggregate(long: pd.DataFrame, unit_column: str) -> pd.DataFrame:
    """Mean/sd per (method, unit, metric) over seeds; unit is target or view."""
    summary = (
        long.groupby(["method", unit_column, "metric"], as_index=False)["value"]
        .agg(mean="mean", sd="std")
        .fillna({"sd": 0.0})  # a single seed has no dispersion, not a missing one
        .sort_values([unit_column, "metric", "mean"], kind="stable")
        .reset_index(drop=True)
    )
    return summary.rename(columns={unit_column: "target"})


def make_figures(run_dir: Path) -> int:
    """Aggregate a run's long artifacts into summary table artifacts.

    Handles both run kinds: ``metrics_long.csv`` (``imp sweep``) becomes
    ``summary.csv``/``summary.tex``; ``harness_long.csv`` (``imp harness``)
    becomes ``harness_summary.csv``/``harness_summary.tex``.

    Args:
        run_dir: A run directory written by ``imp sweep`` or ``imp harness``.

    Returns:
        Process exit code (``0`` on success).
    """
    wrote_any = False
    for filename, unit_column, out_stem in (
        ("metrics_long.csv", "target", "summary"),
        ("harness_long.csv", "view", "harness_summary"),
    ):
        long_path = run_dir / filename
        if not long_path.exists():
            continue
        long = pd.read_csv(long_path)
        if long.empty:
            continue
        summary = _aggregate(long, unit_column)
        summary_csv = run_dir / f"{out_stem}.csv"
        summary.to_csv(summary_csv, index=False)
        summary_tex = run_dir / f"{out_stem}.tex"
        summary_tex.write_text(_to_latex_tabular(summary))
        print(f"imp figures -- aggregated {long_path}")
        print(f"  wrote {summary_csv} ({len(summary)} rows)")
        print(f"  wrote {summary_tex}")
        wrote_any = True

    if not wrote_any:
        raise SystemExit(
            f"No non-empty metrics_long.csv or harness_long.csv under "
            f"{run_dir}; pass a run directory written by `imp sweep` or "
            "`imp harness`."
        )
    return 0
