"""``imp figures``: aggregate a sweep run into the paper's summary artifacts.

Reads a run's ``metrics_long.csv`` and writes, next to it:

* ``summary.csv`` -- mean and standard deviation per (method, target, metric)
  over seeds, the table the manuscript's results tables are built from.
* ``summary.tex`` -- the same aggregation as a LaTeX ``tabular`` for direct
  ``\\input`` into ``paper/tables/`` (written with plain string formatting, so
  no jinja2/matplotlib dependency).

Plots (per-metric method comparisons) are TODO and land behind the ``viz``
extra; tables come first because the paper's claims cite them.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd


def _to_latex_tabular(summary: pd.DataFrame) -> str:
    """Render the summary frame as a plain LaTeX tabular (no jinja2)."""
    lines = [
        "% Generated by `imp figures` -- do not edit by hand.",
        r"\begin{tabular}{llrrr}",
        r"\hline",
        r"method & target & metric & mean & sd \\",
        r"\hline",
    ]
    for record in summary.itertuples(index=False):
        method = str(record.method).replace("_", r"\_")
        target = str(record.target).replace("_", r"\_")
        metric = str(record.metric).replace("_", r"\_")
        lines.append(
            f"{method} & {target} & {metric} & "
            f"{record.mean:,.4f} & {record.sd:,.4f} \\\\"
        )
    lines += [r"\hline", r"\end{tabular}", ""]
    return "\n".join(lines)


def make_figures(run_dir: Path) -> int:
    """Aggregate ``run_dir/metrics_long.csv`` into summary table artifacts.

    Args:
        run_dir: A run directory written by ``imp sweep``.

    Returns:
        Process exit code (``0`` on success).
    """
    metrics_path = run_dir / "metrics_long.csv"
    if not metrics_path.exists():
        raise SystemExit(
            f"{metrics_path} not found; pass a run directory written by `imp sweep`."
        )
    long = pd.read_csv(metrics_path)
    if long.empty:
        raise SystemExit(f"{metrics_path} has no metric rows to aggregate.")

    summary = (
        long.groupby(["method", "target", "metric"], as_index=False)["value"]
        .agg(mean="mean", sd="std")
        .fillna({"sd": 0.0})  # a single seed has no dispersion, not a missing one
        .sort_values(["target", "metric", "mean"], kind="stable")
        .reset_index(drop=True)
    )

    summary_csv = run_dir / "summary.csv"
    summary.to_csv(summary_csv, index=False)
    summary_tex = run_dir / "summary.tex"
    summary_tex.write_text(_to_latex_tabular(summary))

    print(f"imp figures -- aggregated {metrics_path}")
    print(f"  wrote {summary_csv} ({len(summary)} rows)")
    print(f"  wrote {summary_tex}")
    return 0
